all:
#	gcc -o bthandler bthandler.c -lbluetooth -pthread
#	gcc -o tcphandler tcphandler.c -pthread
#	gcc -o srlhandler srlhandler.c -pthread
	gcc  multithreadhandler.c tcphandler.c bthandler.c srlhandler.c commshandler.h -pthread -lbluetooth -o mdpstart

